### ISSUE TITLE
你好，请问一下，你那个微信分享朋友圈是怎么做的，我是直接把你weixin-share给复制到我的lib，然后直接在share.ejs设置的，但是却无法弹出二维码，请问怎么解决

### ISSUE THREAD

**Issue by lone0x0** [lihthub/lihthub.github.io#1]

**Comment by lihthub** [comment]
<img width="731" alt="截屏2021-02-06 上午12 05 52" src="https://user-images.githubusercontent.com/18432386/107059187-72387480-6810-11eb-97be-9f41cc45da2b.png">

**Comment by lone0x0** [comment]
谢谢，已解决

**Comment by lone0x0** [comment]
不过扫描这个二维码之后，直接就出新一个example domain的页面，我刚刚扫了你博客，是可以正常跳转的，请问这个怎么解决

**Comment by lihthub** [comment]
我在你的博客里点击后没有弹出二维码呀，你没有按我发的步骤来吗

**Comment by lone0x0** [comment]
我已经删除了，谢谢啦

**Comment by lone0x0** [comment]
对了 还有一个问题请教您，您博客的站内搜索，我按照你的步骤来，但是搜索出来直接是404页面，请问有啥解决方法吗

**Comment by lihthub** [comment]
我那个 search 插件是很早之前装的，你现在装的话版本不一样了，确实会有问题，前段时间也有一位同学问了跟你同样的问题，我确认了一下，是版本问题，这需要你自己去研究一下了。
